# Generated by Django 6.0.7 on 2026-08-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/%Y/%m/%d/')),
                ('full_name', models.CharField(max_length=120)),
                ('data', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('context', models.TextField()),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
