# Generated by Django 6.0.7 on 2026-08-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='data',
        ),
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(default=None, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='context',
            field=models.TextField(verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='profile/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(allow_unicode=True, verbose_name='Ссылка'),
        ),
    ]
