# Generated by Django 6.0.7 on 2026-08-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_options_remove_profile_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateTimeField(verbose_name='Дата рождения'),
        ),
    ]
