# Generated by Django 6.0.7 on 2026-08-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-birth_date']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default=None, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
